### ISSUE TITLE
[BUG] WordBreakCompoundRewriter is not working as expected

### ISSUE THREAD

**Issue by JohannesDaniel** [querqy/querqy-opensearch#11]
When using the word break rewriter in a query, the following exception is thrown:
```
[querqy-example/t3iVrtE-TXC5S2dfxjWV9Q] QueryShardException[failed to create query: this IndexReader is closed]; nested: AlreadyClosedException[this IndexReader is closed];
	at org.opensearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:402)
	at org.opensearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:385)
	at org.opensearch.search.SearchService.parseSource(SearchService.java:902)
	at org.opensearch.search.SearchService.createContext(SearchService.java:739)
	at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:441)
	at org.opensearch.search.SearchService.access$500(SearchService.java:154)
	at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:414)
	at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:71)
	at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:86)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50)
	at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:57)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:756)
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.apache.lucene.store.AlreadyClosedException: this IndexReader is closed
	at org.apache.lucene.index.IndexReader.ensureOpen(IndexReader.java:257)
	at org.apache.lucene.index.CompositeReader.getContext(CompositeReader.java:99)
	at org.apache.lucene.index.CompositeReader.getContext(CompositeReader.java:53)
	at org.apache.lucene.search.IndexSearcher.<init>(IndexSearcher.java:183)
	at org.apache.lucene.search.IndexSearcher.<init>(IndexSearcher.java:170)
	at querqy.lucene.contrib.rewrite.wordbreak.Collector.<init>(Collector.java:142)
	at querqy.lucene.contrib.rewrite.wordbreak.MorphologicalWordBreaker.breakWord(MorphologicalWordBreaker.java:61)
	at querqy.lucene.contrib.rewrite.wordbreak.WordBreakCompoundRewriter.decompound(WordBreakCompoundRewriter.java:177)
	at querqy.lucene.contrib.rewrite.wordbreak.WordBreakCompoundRewriter.visit(WordBreakCompoundRewriter.java:161)
	at querqy.lucene.contrib.rewrite.wordbreak.WordBreakCompoundRewriter.visit(WordBreakCompoundRewriter.java:27)
	at querqy.model.Term.accept(Term.java:59)
	at querqy.lucene.contrib.rewrite.wordbreak.WordBreakCompoundRewriter.visit(WordBreakCompoundRewriter.java:145)
	at querqy.lucene.contrib.rewrite.wordbreak.WordBreakCompoundRewriter.visit(WordBreakCompoundRewriter.java:27)
	at querqy.model.DisjunctionMaxQuery.accept(DisjunctionMaxQuery.java:25)
	at querqy.model.AbstractNodeVisitor.visit(AbstractNodeVisitor.java:15)
	at querqy.lucene.contrib.rewrite.wordbreak.WordBreakCompoundRewriter.rewrite(WordBreakCompoundRewriter.java:91)
	at querqy.rewrite.RewriteChain.rewrite(RewriteChain.java:66)
	at querqy.lucene.QueryParsingController.process(QueryParsingController.java:197)
	at querqy.opensearch.QuerqyProcessor.parseQuery(QuerqyProcessor.java:76)
	at querqy.opensearch.query.QuerqyQueryBuilder.doToQuery(QuerqyQueryBuilder.java:205)
	at org.opensearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:116)
	at org.opensearch.index.query.QueryShardContext.lambda$toQuery$3(QueryShardContext.java:386)
	at org.opensearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:398)
	... 15 more
```

The word break rewriter uses the index as dictionary during the rewriting. `querqy.opensearch.rewriter.WordBreakCompoundRewriterFactory#createRewriterFactory` passes an IndexShard reference to the rewriter when loading it. This reference is used later to get an IndexReader reference, which is used to apply the index lookups.

**Comment by ps48** [comment]
Issue is resolved with #17
